### ISSUE TITLE
Redis output is tsv not csv

### ISSUE THREAD

**Issue by seveibar** [rpiml/okcollege-college-training-preprocessor#4]
A quick glance at the redis output shows that it is tab separated not comma separated.

**Comment by jko0531** [comment]
It can't be comma separated because some colleges have a comma in their name.

**Comment by seveibar** [comment]
Most csv parsers should support quoted entries or have an escaping option-
even as is the files and keys should be correctly labeled with tsv and not
csv if they represent tab delimited content.

Right now the specification (in the system diagram of dev) calls for csv-
it may be simpler to switch to tsv but we need to change the relevant api
documentation to reflect that. i think csv is more popular so im a bit
hesitant to change
